### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation) in branch "ios_support"

### ISSUE THREAD

**Issue by axenovV** [perfaram/PFSystemKit#10]
Hello. When i build framework i have this issue. Could you help with this ?
<img width="1280" alt="2015-10-17 19 57 52" src="https://cloud.githubusercontent.com/assets/9257530/10560124/d7d4a746-7509-11e5-9a4a-86818142b4e8.png">

**Comment by perfaram** [comment]
I'll have a check.

**Comment by perfaram** [comment]
Okay, just cloned the repo in a clean directory... had no problems. Are you sure you didn't change something ?

**Comment by axenovV** [comment]
sure. my friend has just downloaded the branch and he has the same issue. am I supposed to just clean the directory?

**Comment by axenovV** [comment]
I have cleaned the derived data, but there is still the same issue.

**Comment by perfaram** [comment]
Ohoh... so I'm the only one where it works. Which Xcode ? Which OS X ? 

Note that if you can fix it, I'd happily merge your branch.

**Comment by perfaram** [comment]
Note that if you can fix it, I'd happily merge your branch.

**Comment by axenovV** [comment]
OS Capitan, Xcode 7. I'll try, and I've found a mistake in a master branch. Framework for ios platform builds without few classes.

**Comment by perfaram** [comment]
OK. I'm still under Yosemite, Xcode 7 beta.

**Comment by perfaram** [comment]
Updated today, will now try.

**Comment by axenovV** [comment]
Still does not operate.And commit can't be seen in the branch.

**Comment by perfaram** [comment]
I updated _OSX_, not the repo.

**Comment by perfaram** [comment]
Think is is now fixed, thanks for reporting. Feel free to reopen if errors appear :warning:
