### ISSUE TITLE
Build errors with Xcode 7.2.1 (and 7.3 beta)

### ISSUE THREAD

**Issue by zstrickler** [perfaram/PFSystemKit#11]
Just downloaded and am attempting to build, but I am getting several errors (specifically in PFSK_iOS.mm).

`PFSK_iOS.mm:106:13: Property implementation must have its declaration in interface 'PFSystemKit'`
`PFSK_iOS.mm:29:25: No visible @interface for 'PFSystemKit' declares the selector 'updatePlatformReport:'`

I've racked my brain trying to figure it out, but I'm at a loss. Any help would be appreciated!

**Comment by perfaram** [comment]
Whoops... Looks like there's really an issue there. I think I forgot to push some commit last time I made changes.

**Comment by perfaram** [comment]
3d4dea2 should have fixed, let me know.

**Comment by sjwhyte** [comment]
@perfaram Can I ask, has this framework ever been used in an App that Apple approved? I like the library, but don't want it to get rejected.

**Comment by perfaram** [comment]
As long as you're not using methods placed between `asrg_get_out_of_my_way` flags, you should be ok.
If you have another question please open another issue.
