### ISSUE TITLE
Need confirmation 

### ISSUE THREAD

**Issue by hardikdevios** [perfaram/PFSystemKit#2]
First of all thanks for this great lib, have few doubts .. does it compile with Appstore Guidelines ?. Or there will be a risk of the App Rejection ?  

One more thing currently Build not passing the success .. its failing to Run.

**Comment by perfaram** [comment]
Actually iOS support isn't that good - I'll be working on it tomorrow. Moreover, it's quite hard for me to test, because I don't have an Apple Developer certificate...

**Comment by hardikdevios** [comment]
@perfaram i hope there will reject the APP see this 
http://stackoverflow.com/questions/3132619/getting-the-serial-number-not-udid-of-iphone-programmatically?lq=1
your lib is using the IOKit so this will not allow by iOS

**Comment by perfaram** [comment]
The iOS version - which doesn't truly exist ATM - does NOT link against IOKit. And will never do so, except if I make a _separate_ version, i.e. for jailbreak tweaks or apps.
Have a look at the Omnistat app (by Matthieu Bollard - @mattlawer), if you'd like to see what will the iOS version be able to do.

**Comment by perfaram** [comment]
BTW, feel free to reopen another issue if needed - or to fork & PR if you feel you can help !

**Comment by perfaram** [comment]
See #3
