### ISSUE TITLE
How to get equipment uniquely identified?

### ISSUE THREAD

**Issue by xhzengAIB** [perfaram/PFSystemKit#9]
@perfaram 

Hi！
How to get equipment uniquely identified?

Jack

**Comment by perfaram** [comment]
iDevice or Macintosh ?

**Comment by perfaram** [comment]
For Macintosh, it's on the main page (screenshot) : 

```
        PFSystemKit* systemKit = [PFSystemKit investigate];
        NSString* UUID = [systemKit.platformReport hardwareUUID];
        NSLog(@"UUID : %@", UUID);
```

Apple made UUID retrieval impossible on iOS around iOS 5, as such, you'll have to implement your own method — or use ready-made solutions such as https://github.com/makotokw/CocoaWZYDevice.
However, if you implement your own and feel like sharing it, just open a Pull request !

**Comment by xhzengAIB** [comment]
Hi! @perfaram 

```
    PFSystemKit* systemKit = [PFSystemKit investigate];
    NSString* UUID = [systemKit.platformReport hardwareUUID];
```

This UUID is equipment uniquely identified?  Never change?
Jack

**Comment by perfaram** [comment]
It is not supposed to. Who knows, even serial can be changed !

**Comment by xhzengAIB** [comment]
@perfaram 
Thanks!

**Comment by perfaram** [comment]
You welcome !
